title: Natan Matos # your name (or website title) here
logo: "images/IMG_vv1267.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Graduate in Data Science and Software Engineering. I have extensive experience in regression, NLP, classification models and knowledge of the 
  their functioning. Strong communication skills and data analysis, with experience in marketing data.
  <br><br>
  <a href="https://www.linkedin.com/in/natan-matos/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

colors:
  crimson: '#900C3F'
